// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALqYIb4sWhzuiRka14GS3EBz2kj4YQeLE',
    appId: '1:683186633513:web:12107667ba500f0b12d538',
    messagingSenderId: '683186633513',
    projectId: 'redditclone-72e6f',
    authDomain: 'redditclone-72e6f.firebaseapp.com',
    storageBucket: 'redditclone-72e6f.appspot.com',
    measurementId: 'G-QGX0Y4K872',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPYk7y2-UweRgVFVhYdEjb1lctnNVJfE',
    appId: '1:683186633513:android:d26b0c7e15632c9412d538',
    messagingSenderId: '683186633513',
    projectId: 'redditclone-72e6f',
    storageBucket: 'redditclone-72e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RrDkMjQSLq-8GOnWQYD0th8SnFGbv2A',
    appId: '1:683186633513:ios:1db100bed022b05d12d538',
    messagingSenderId: '683186633513',
    projectId: 'redditclone-72e6f',
    storageBucket: 'redditclone-72e6f.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RrDkMjQSLq-8GOnWQYD0th8SnFGbv2A',
    appId: '1:683186633513:ios:1db100bed022b05d12d538',
    messagingSenderId: '683186633513',
    projectId: 'redditclone-72e6f',
    storageBucket: 'redditclone-72e6f.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALqYIb4sWhzuiRka14GS3EBz2kj4YQeLE',
    appId: '1:683186633513:web:3a17e1fe772774b512d538',
    messagingSenderId: '683186633513',
    projectId: 'redditclone-72e6f',
    authDomain: 'redditclone-72e6f.firebaseapp.com',
    storageBucket: 'redditclone-72e6f.appspot.com',
    measurementId: 'G-E6E37D1NFV',
  );
}
